#server config
server:
  port: 8080
  tomcat:
    basedir: "/"

#spring config
spring:
  application:
    name: swagger-kubernetes

#swagger kubernetes config
swagger:
  kubernetes:
    connect:
      url: ${KUBERNETES_CONNECT_URL:https://kubernetes.default.svc.cluster.local}
      token: ${KUBERNETES_CONNECT_TOKEN:}
  discovery:
    namespace: ${DISCOVERY_NAMESPACE:}
    interval: ${DISCOVERY_INITIAL_INTERVAL:60}
    url: ${DISCOVERY_URL:}
    portType: ${DISCOVERY_PORT_TYPE:ClusterIP}
  global:
    docApiPath: ${SWGGER_API_PATH:/v2/api-docs}
    ignoreServices: swagger-kubernetes,${IGNORE_SERVICES:}

#manager
management:
  server:
    port:  ${ACTUATOR_PORT:${server.port}}
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_TYPE:*}